title: Material Docs
description: >
  Jekyll theme for documentation üìù built with material web components

# lang: en
# twitter: fernandopasik

# author:
#   name: Fernando Pasik
#   url: https://fernandopasik.com

main_nav:
  - title: Get Started
    url: /getting-started
  - title: API
    url: /api

content_table:
  - title: Get Started
    url: /getting-started
  - title: API
    links:
      - title: home
        url: /api/home
      - title: page
        url: /api/page

google_analytics: G-2MWB7NGC05

sass:
  style: compressed

plugins:
  # already included in github, but to enable local dev
  - jekyll-github-metadata
  - jekyll-seo-tag

exclude:
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE
  - eslint.config.js
  - package.json
  - package-lock.json
  - README.md
  - '*.gemspec'
